import { CityData } from './types';

export const CITIES: CityData[] = [
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    population: 0.87,
    gdp: 110,
    annualBudget: 3.8,
    co2Total: 2.1,
    co2PerCapita: 2.4,
    renewableEnergy: 58,
    publicTransit: 62,
    airQuality: 28,
    crimeRate: 52,
    infrastructureInvestment: 18,
    publicTrust: 72,
    debtRatio: 42,
    greenInvestment: 12,
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    population: 3.75,
    gdp: 155,
    annualBudget: 34,
    co2Total: 18,
    co2PerCapita: 4.8,
    renewableEnergy: 44,
    publicTransit: 74,
    airQuality: 36,
    crimeRate: 71,
    infrastructureInvestment: 15,
    publicTrust: 58,
    debtRatio: 58,
    greenInvestment: 9,
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    population: 7.4,
    gdp: 90,
    annualBudget: 6.2,
    co2Total: 8.5,
    co2PerCapita: 1.15,
    renewableEnergy: 72,
    publicTransit: 55,
    airQuality: 68,
    crimeRate: 195,
    infrastructureInvestment: 11,
    publicTrust: 34,
    debtRatio: 29,
    greenInvestment: 5,
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    population: 3.3,
    gdp: 105,
    annualBudget: 22,
    co2Total: 32,
    co2PerCapita: 9.7,
    renewableEnergy: 14,
    publicTransit: 21,
    airQuality: 82,
    crimeRate: 12,
    infrastructureInvestment: 24,
    publicTrust: 68,
    debtRatio: 18,
    greenInvestment: 7,
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    population: 10.5,
    gdp: 130,
    annualBudget: 4.8,
    co2Total: 28,
    co2PerCapita: 2.67,
    renewableEnergy: 12,
    publicTransit: 38,
    airQuality: 145,
    crimeRate: 68,
    infrastructureInvestment: 9,
    publicTrust: 41,
    debtRatio: 22,
    greenInvestment: 3,
  },
  {
    id: 'london',
    name: 'London',
    country: 'UK',
    population: 9.0,
    gdp: 665,
    annualBudget: 22,
    co2Total: 35,
    co2PerCapita: 3.9,
    renewableEnergy: 46,
    publicTransit: 67,
    airQuality: 42,
    crimeRate: 83,
    infrastructureInvestment: 17,
    publicTrust: 55,
    debtRatio: 48,
    greenInvestment: 10,
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    population: 9.2,
    gdp: 225,
    annualBudget: 10.5,
    co2Total: 24,
    co2PerCapita: 2.6,
    renewableEnergy: 22,
    publicTransit: 48,
    airQuality: 112,
    crimeRate: 148,
    infrastructureInvestment: 10,
    publicTrust: 28,
    debtRatio: 35,
    greenInvestment: 4,
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    country: 'Kenya',
    population: 4.4,
    gdp: 34,
    annualBudget: 1.1,
    co2Total: 3.8,
    co2PerCapita: 0.86,
    renewableEnergy: 81,
    publicTransit: 42,
    airQuality: 98,
    crimeRate: 220,
    infrastructureInvestment: 8,
    publicTrust: 30,
    debtRatio: 31,
    greenInvestment: 2,
  },
  {
    id: 'new-york',
    name: 'New York',
    country: 'USA',
    population: 8.3,
    gdp: 1100,
    annualBudget: 107,
    co2Total: 49,
    co2PerCapita: 5.9,
    renewableEnergy: 32,
    publicTransit: 56,
    airQuality: 50,
    crimeRate: 118,
    infrastructureInvestment: 12,
    publicTrust: 48,
    debtRatio: 71,
    greenInvestment: 8,
  },
  {
    id: 'oslo',
    name: 'Oslo',
    country: 'Norway',
    population: 0.7,
    gdp: 90,
    annualBudget: 7.2,
    co2Total: 1.8,
    co2PerCapita: 2.57,
    renewableEnergy: 92,
    publicTransit: 58,
    airQuality: 18,
    crimeRate: 38,
    infrastructureInvestment: 22,
    publicTrust: 81,
    debtRatio: 30,
    greenInvestment: 16,
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    population: 2.1,
    gdp: 185,
    annualBudget: 10,
    co2Total: 5.2,
    co2PerCapita: 2.5,
    renewableEnergy: 38,
    publicTransit: 79,
    airQuality: 44,
    crimeRate: 62,
    infrastructureInvestment: 16,
    publicTrust: 51,
    debtRatio: 55,
    greenInvestment: 11,
  },
  {
    id: 'riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    population: 7.5,
    gdp: 250,
    annualBudget: 38,
    co2Total: 56,
    co2PerCapita: 7.5,
    renewableEnergy: 3,
    publicTransit: 12,
    airQuality: 118,
    crimeRate: 18,
    infrastructureInvestment: 28,
    publicTrust: 61,
    debtRatio: 12,
    greenInvestment: 4,
  },
  {
    id: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    population: 6.3,
    gdp: 112,
    annualBudget: 6.5,
    co2Total: 10,
    co2PerCapita: 1.59,
    renewableEnergy: 48,
    publicTransit: 44,
    airQuality: 92,
    crimeRate: 88,
    infrastructureInvestment: 14,
    publicTrust: 39,
    debtRatio: 26,
    greenInvestment: 6,
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    population: 9.7,
    gdp: 815,
    annualBudget: 38,
    co2Total: 44,
    co2PerCapita: 4.5,
    renewableEnergy: 18,
    publicTransit: 82,
    airQuality: 58,
    crimeRate: 26,
    infrastructureInvestment: 19,
    publicTrust: 54,
    debtRatio: 38,
    greenInvestment: 8,
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    country: 'China',
    population: 24.9,
    gdp: 700,
    annualBudget: 55,
    co2Total: 188,
    co2PerCapita: 7.5,
    renewableEnergy: 22,
    publicTransit: 71,
    airQuality: 88,
    crimeRate: 22,
    infrastructureInvestment: 21,
    publicTrust: 65,
    debtRatio: 44,
    greenInvestment: 7,
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    population: 5.8,
    gdp: 466,
    annualBudget: 72,
    co2Total: 44,
    co2PerCapita: 7.6,
    renewableEnergy: 4,
    publicTransit: 68,
    airQuality: 36,
    crimeRate: 11,
    infrastructureInvestment: 25,
    publicTrust: 76,
    debtRatio: 134,
    greenInvestment: 9,
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    population: 1.0,
    gdp: 155,
    annualBudget: 6.8,
    co2Total: 2.0,
    co2PerCapita: 2.0,
    renewableEnergy: 88,
    publicTransit: 65,
    airQuality: 16,
    crimeRate: 48,
    infrastructureInvestment: 20,
    publicTrust: 78,
    debtRatio: 32,
    greenInvestment: 18,
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    population: 13.9,
    gdp: 1680,
    annualBudget: 70,
    co2Total: 68,
    co2PerCapita: 4.9,
    renewableEnergy: 26,
    publicTransit: 86,
    airQuality: 30,
    crimeRate: 14,
    infrastructureInvestment: 18,
    publicTrust: 66,
    debtRatio: 68,
    greenInvestment: 10,
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    population: 2.9,
    gdp: 205,
    annualBudget: 13.5,
    co2Total: 20,
    co2PerCapita: 6.9,
    renewableEnergy: 34,
    publicTransit: 45,
    airQuality: 35,
    crimeRate: 40,
    infrastructureInvestment: 16,
    publicTrust: 64,
    debtRatio: 52,
    greenInvestment: 8,
  },
  {
    id: 'warsaw',
    name: 'Warsaw',
    country: 'Poland',
    population: 1.8,
    gdp: 65,
    annualBudget: 3.2,
    co2Total: 11,
    co2PerCapita: 6.1,
    renewableEnergy: 16,
    publicTransit: 52,
    airQuality: 78,
    crimeRate: 44,
    infrastructureInvestment: 14,
    publicTrust: 46,
    debtRatio: 40,
    greenInvestment: 6,
  },
];

export function getCityById(id: string): CityData | undefined {
  return CITIES.find(c => c.id === id);
}
